version: 2

sources:
  - name: nba
    description: "NBA data from external tables in Google Cloud Storage"
    tables:


      - name: raw_active_players
        description: "NBA active players raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landingzone/nba/active_players/2025/raw_nba_active_players_2025.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: id
            description: "Unique player identifier"
            data_type: integer
          - name: first_name
            description: "Player first name"
            data_type: string
          - name: last_name
            description: "Player last name"
            data_type: string
          - name: position
            description: "Player position"
            data_type: string
          - name: height
            description: "Player height"
            data_type: string
          - name: weight
            description: "Player weight"
            data_type: string
          - name: jersey_number
            description: "Player jersey number"
            data_type: string
          - name: college
            description: "Player college"
            data_type: string
          - name: country
            description: "Player country"
            data_type: string
          - name: draft_year
            description: "Draft year"
            data_type: integer
          - name: draft_round
            description: "Draft round"
            data_type: integer
          - name: draft_number
            description: "Draft number"
            data_type: integer
          - name: team
            description: "Player team information (STRUCT with id, name, abbreviation, etc.)"
            data_type: struct

      - name: raw_team_standings
        description: "NBA team standings raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landingzone/nba/team_standings/2025/raw_nba_team_standings_2025.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: team
            description: "Team information (STRUCT with id, name, abbreviation, conference, division, etc.)"
            data_type: struct
          - name: conference_record
            description: "Conference record (e.g., '10-1')"
            data_type: string
          - name: conference_rank
            description: "Rank within conference"
            data_type: integer
          - name: division_record
            description: "Division record (e.g., '5-0')"
            data_type: string
          - name: division_rank
            description: "Rank within division"
            data_type: integer
          - name: wins
            description: "Total number of wins"
            data_type: integer
          - name: losses
            description: "Total number of losses"
            data_type: integer
          - name: home_record
            description: "Home games record (e.g., '8-0')"
            data_type: string
          - name: road_record
            description: "Away games record (e.g., '2-1')"
            data_type: string
          - name: season
            description: "Season year"
            data_type: integer

      - name: raw_season_averages_general_advanced
        description: "NBA season averages general advanced raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landingzone/nba/season_averages/2025/raw_nba_season_averages_2025-general-advanced.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: player
            description: "Player information (STRUCT with id, first_name, last_name, position, height, weight, etc.)"
            data_type: struct
          - name: season
            description: "Season year (e.g., 2024)"
            data_type: integer
          - name: season_type
            description: "Season type (regular, playoffs, ist, playin)"
            data_type: string
          - name: stats
            description: "Season statistics (STRUCT with various statistical fields based on category/type)"
            data_type: struct

      - name: raw_season_averages_general_base
        description: "NBA season averages general base raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landingzone/nba/season_averages/2025/raw_nba_season_averages_2025-general-base.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: player
            description: "Player information (STRUCT with id, first_name, last_name, position, height, weight, jersey_number, college, country, draft_year, draft_round, draft_number)"
            data_type: struct
          - name: season
            description: "Season year (e.g., 2024)"
            data_type: integer
          - name: season_type
            description: "Season type (regular, playoffs, ist, playin)"
            data_type: string
          - name: stats
            description: "Season statistics (STRUCT with base statistical fields like pts, reb, ast, fg_pct, etc.)"
            data_type: struct

      - name: raw_season_averages_shooting_by_zone
        description: "NBA season averages shooting by zone raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landingzone/nba/season_averages/2025/raw_nba_season_averages_2025-shooting-by-zone.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: player
            description: "Player information (STRUCT with id, first_name, last_name, position, height, weight, jersey_number, college, country, draft_year, draft_round, draft_number)"
            data_type: struct
          - name: season
            description: "Season year (e.g., 2025)"
            data_type: integer
          - name: season_type
            description: "Season type (regular, playoffs, ist, playin)"
            data_type: string
          - name: stats
            description: "Season statistics (STRUCT with shooting by zone fields: corner_3, above_the_break_3, restricted_area, in_the_paint_non_ra, mid_range, backcourt - all with fga, fgm, and fg_pct)"
            data_type: struct

      - name: raw_games
        description: "NBA games raw data from Balldontlie API (NDJSON format). Each record contains season, date, total_games, and an array of games."
        external:
          location: "gs://smartbetting-landingzone/nba/games/2025/raw_nba_games_2025_*.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: season
            description: "Season year (e.g., 2025)"
            data_type: string
          - name: date
            description: "Game date (YYYY-MM-DD)"
            data_type: string
          - name: total_games
            description: "Total number of games on this date"
            data_type: string
          - name: games
            description: "Array of game objects, each containing game details"
            data_type: array

      - name: raw_game_player_stats
        description: "NBA game player stats raw data from Balldontlie API (NDJSON format)"
        external:
          location: "gs://smartbetting-landingzone/nba/game_player_stats/2025/raw_nba_game_player_stats_2025_*.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: id
            description: "Unique stat record identifier"
            data_type: float
          - name: min
            description: "Minutes played (as string)"
            data_type: string
          - name: fgm
            description: "Field goals made"
            data_type: float
          - name: fga
            description: "Field goals attempted"
            data_type: float
          - name: fg_pct
            description: "Field goal percentage"
            data_type: float
          - name: fg3m
            description: "Three-pointers made"
            data_type: float
          - name: fg3a
            description: "Three-pointers attempted"
            data_type: float
          - name: fg3_pct
            description: "Three-point percentage"
            data_type: float
          - name: ftm
            description: "Free throws made"
            data_type: float
          - name: fta
            description: "Free throws attempted"
            data_type: float
          - name: ft_pct
            description: "Free throw percentage"
            data_type: float
          - name: oreb
            description: "Offensive rebounds"
            data_type: float
          - name: dreb
            description: "Defensive rebounds"
            data_type: float
          - name: reb
            description: "Total rebounds"
            data_type: float
          - name: ast
            description: "Assists"
            data_type: float
          - name: stl
            description: "Steals"
            data_type: float
          - name: blk
            description: "Blocks"
            data_type: float
          - name: turnover
            description: "Turnovers"
            data_type: float
          - name: pf
            description: "Personal fouls"
            data_type: float
          - name: pts
            description: "Points scored"
            data_type: float
          - name: player
            description: "Player information (STRUCT with id, first_name, last_name, position, etc.)"
            data_type: struct
          - name: team
            description: "Team information (STRUCT with id, name, abbreviation, conference, division, etc.)"
            data_type: struct
          - name: game
            description: "Game information (STRUCT with id, date, season, status, etc.)"
            data_type: struct

      - name: raw_player_injuries
        description: "NBA player injuries raw data (NDJSON format)"
        external:
          location: "gs://smartbetting-landingzone/nba/player_injuries/2025/raw_nba_player_injuries_2025.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: season
            description: "Season year (e.g., 2025)"
            data_type: integer
          - name: total_injuries
            description: "Total number of injuries"
            data_type: integer
          - name: player
            description: "Player information (STRUCT with id, first_name, last_name, position, height, weight, jersey_number, college, country, draft_year, draft_round, draft_number, team_id)"
            data_type: struct
          - name: return_date
            description: "Expected return date (YYYY-MM-DD format, parsed to DATE in staging)"
            data_type: string
          - name: description
            description: "Injury description and details"
            data_type: string
          - name: status
            description: "Injury status (e.g., Doubtful, Out, Questionable)"
            data_type: string

      - name: raw_player_props
        description: "NBA player props raw data from DraftKings (NDJSON format)"
        external:
          location: "gs://smartbetting-landingzone/nba/player_props/2025/draftkings/raw_nba_player_props_2025-*.json"
          options:
            format: NEWLINE_DELIMITED_JSON
        columns:
          - name: id
            description: "Unique prop identifier (renamed to prop_id in staging)"
            data_type: integer
          - name: player_id
            description: "Player identifier"
            data_type: integer
          - name: game_id
            description: "Game identifier"
            data_type: integer
          - name: season
            description: "Season year (e.g., 2025)"
            data_type: integer
          - name: vendor
            description: "Sportsbook vendor (e.g., draftkings)"
            data_type: string
          - name: prop_type
            description: "Type of prop (e.g., points, rebounds, assists)"
            data_type: string
          - name: line_value
            description: "Line value for the prop (string, converted to numeric in staging)"
            data_type: string
          - name: market
            description: "Market information (STRUCT with type: market type e.g. milestone extracted as market_type, and odds: integer converted to decimal format as (odds/100) + 1 extracted as market_odds)"
            data_type: struct
          - name: total_props
            description: "Total number of props"
            data_type: integer
          - name: updated_at
            description: "Last update timestamp (ISO 8601 format)"
            data_type: string